management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json, application/xml, text/html, text/plain

spring:
  application:
    name: synctalk

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      leak-detection-threshold: 30000
      auto-commit: true
      keepalive-time: 30000
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          fetch_size: 20
        order_inserts: true
        order_updates: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDIS_PASSWORD:}
      timeout: 60000

logging:
  level:
    liquibase: DEBUG
    org.springframework.security: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: 36000000
  issuer: synctalk-api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

dev:
  open-api:
    dev-url: https://synctalk-production-35bf.up.railway.app/api/v1

